=== lauralaca/sew/F1Desktop/xml/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.uniovi.es"
	xmlns="http://www.uniovi.es"
	elementFormDefault="qualified">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitud" />
				<xs:element ref="anchura" />
				<xs:element ref="fecha" />
				<xs:element ref="hora" />
				<xs:element ref="vueltas" />
				<xs:element ref="localidad" />
				<xs:element ref="país" />
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
				<xs:element minOccurs="1" maxOccurs="5" ref="fotografía" />
				<xs:element minOccurs="0" maxOccurs="3" ref="vídeo" />
				<xs:element ref="coordenadas" />
				<xs:element ref="tramos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="unidad" type="xs:string" use="required" />
					<xs:attribute name="valor" type="xs:decimal" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="anchura">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="unidad" type="xs:string" use="required" />
					<xs:attribute name="valor" type="xs:decimal" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha" type="xs:date" />
	<xs:element name="hora" type="xs:time" />
	<xs:element name="vueltas" type="xs:integer" />
	<xs:element name="localidad" type="xs:string" />
	<xs:element name="país" type="xs:string" />
	<xs:element name="referencia" type="xs:anyURI" />
	<xs:element name="fotografía" type="xs:anyURI" />
	<xs:element name="vídeo" type="xs:anyURI" />
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="latitud" type="Latitud" use="required"  />
					<xs:attribute name="longitud" type="Longitud" use="required" />
					<xs:attribute name="altitud" type="Altitud" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="Latitud">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-90"/>
			<xs:maxInclusive value="90"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Longitud">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-180"/>
			<xs:maxInclusive value="180"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Altitud">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="5000"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="coordenadas" />
				<xs:element ref="sector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="unidad" type="xs:string" use="required" />
					<xs:attribute name="valor" type="xs:decimal" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="sector" type="xs:string" />
	
</xs:schema>

=== lauralaca/sew/F1Desktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito xmlns="http://www.uniovi.es"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.uniovi.es circuito.xsd">
<nombre>"Losail"</nombre>
<longitud unidad= "m" valor="5380"></longitud>
<anchura unidad="m" valor="12"></anchura>
<fecha>2024-12-01</fecha>
<hora>17:00:00</hora>
<vueltas>57</vueltas>
<localidad>"Lusail"</localidad>
<país>"Qatar"</país>
<referencia>https://es.wikipedia.org/wiki/Circuito_Internacional_de_Losail</referencia>
<referencia>https://www.formula1.com/en/racing/2024/qatar</referencia>
<referencia>https://www.f1cfa.com/post.asp?topiccode=z3pp0l9ha7r8w2r5l1k6g9h6t1dd4j</referencia>
<fotografía>"grafico.png"</fotografía>
<fotografía>"panoramica1.webp"</fotografía>
<fotografía>"panoramica2.jpg"</fotografía>
<vídeo>"firstViewLosail.mp4"</vídeo>
<coordenadas latitud="25.489230777050782" longitud="51.44959893070764" altitud="11.6"></coordenadas>
<tramos>
    <tramo>
    <distancia unidad="m" valor="429.34"></distancia>
    <coordenadas latitud="25.492597371505127" longitud="51.447493611374796" altitud="11"></coordenadas>
    <sector>"1"</sector>
</tramo>
<tramo>
    <distancia unidad="m" valor="168.89"></distancia>
    <coordenadas latitud="25.493243962553084" longitud="51.44854202553417" altitud="11"></coordenadas>
    <sector>"1"</sector>
</tramo>
<tramo>
    <distancia unidad="m" valor="136.99"></distancia>
    <coordenadas latitud="25.4926011600162" longitud="51.449700982470404" altitud="10"></coordenadas>
    <sector>"1"</sector>
</tramo>
<tramo>
    <distancia unidad="m" valor="154.20"></distancia>
    <coordenadas latitud="25.493123977344915" longitud="51.45073405790437" altitud="11"></coordenadas>
    <sector>"1"</sector>
</tramo>
<tramo>
    <distancia unidad="m" valor="116.75"></distancia>
    <coordenadas latitud="25.494166026877014" longitud="51.45071212762277" altitud="11"></coordenadas>
    <sector>"1"</sector>
</tramo>
<tramo>
    <distancia unidad="m" valor="80.07"></distancia>
    <coordenadas latitud="25.494796295408644" longitud="51.45099003833352" altitud="11"></coordenadas>
    <sector>"1"</sector>
</tramo>
<tramo>
    <distancia unidad="m" valor="310.67"></distancia>
    <coordenadas latitud="25.496887454087844" longitud="51.45307189793061" altitud="10"></coordenadas>
    <sector>"1"</sector>
</tramo>
<tramo>
    <distancia unidad="m" valor="114.05"></distancia>
    <coordenadas latitud="25.49689659448377" longitud="51.45408142510728" altitud="10"></coordenadas>
    <sector>"1"</sector>
</tramo>
<tramo>
    <distancia unidad="m" valor="50.07"></distancia>
    <coordenadas latitud="25.49658690212462" longitud="51.45446639494586" altitud="10"></coordenadas>
    <sector>"1"</sector>
</tramo>
<tramo>
    <distancia unidad="m" valor="114.27"></distancia>
    <coordenadas latitud="25.49568741593802" longitud="51.45451042036804" altitud="11"></coordenadas>
    <sector>"1"</sector>
</tramo>
<tramo>
    <distancia unidad="m" valor="101.81"></distancia>
    <coordenadas latitud="25.494996671631498" longitud="51.45383294137276" altitud="11"></coordenadas>
    <sector>"2"</sector>
</tramo>
<tramo>
    <distancia unidad="m" valor="99.25"></distancia>
    <coordenadas latitud="25.494349567876142" longitud="51.45317975307143" altitud="12"></coordenadas>
    <sector>"2"</sector>
</tramo>
<tramo>
    <distancia unidad="m" valor="40.23"></distancia>
    <coordenadas latitud="25.49402181146157" longitud="51.45313680156017" altitud="12"></coordenadas>
    <sector>"2"</sector>
</tramo>
<tramo>
    <distancia unidad="m" valor="54.62"></distancia>
    <coordenadas latitud="25.493934344496033" longitud="51.453609145282584" altitud="12"></coordenadas>
    <sector>"2"</sector>
</tramo>
<tramo>
    <distancia unidad="m" valor="270.70"></distancia>
    <coordenadas latitud="25.49484500316108" longitud="51.45612087861001" altitud="13"></coordenadas>
    <sector>"2"</sector>
</tramo>
<tramo>
    <distancia unidad="m" valor="173.14"></distancia>
    <coordenadas latitud="25.493893942175603" longitud="51.45672175760297" altitud="12"></coordenadas>
    <sector>"2"</sector>
</tramo>
<tramo>
    <distancia unidad="m" valor="203.65"></distancia>
    <coordenadas latitud="25.492343368297465" longitud="51.45571055575678" altitud="11"></coordenadas>
    <sector>"2"</sector>
</tramo>
<tramo>
    <distancia unidad="m" valor="89.39"></distancia>
    <coordenadas latitud="25.491807925438454" longitud="51.455151984506165" altitud="11"></coordenadas>
    <sector>"2"</sector>
</tramo>
<tramo>
    <distancia unidad="m" valor="132.97"></distancia>
    <coordenadas latitud="25.491538569195185" longitud="51.45386050565854" altitud="11"></coordenadas>
    <sector>"2"</sector>
</tramo>
<tramo>
    <distancia unidad="m" valor="82.41"></distancia>
    <coordenadas latitud="25.490932326524813" longitud="51.453585254596554" altitud="11"></coordenadas>
    <sector>"2"</sector>
</tramo>
<tramo>
    <distancia unidad="m" valor="107.51"></distancia>
    <coordenadas latitud="25.490271711571808" longitud="51.45435986629674" altitud="12"></coordenadas>
    <sector>"2"</sector>
</tramo>
<tramo>
    <distancia unidad="m" valor="105.7"></distancia>
    <coordenadas latitud="25.489885108481744" longitud="51.45530702428034" altitud="12"></coordenadas>
    <sector>"2"</sector>
</tramo>
<tramo>
    <distancia unidad="m" valor="259.29"></distancia>
    <coordenadas latitud="25.48993851516368" longitud="51.457860019934174" altitud="12"></coordenadas>
    <sector>"2"</sector>    
</tramo>
<tramo>
    <distancia unidad="m" valor="187.62"></distancia>
    <coordenadas latitud="25.489493645638728" longitud="51.45948472256542" altitud="12"></coordenadas>
    <sector>"3"</sector>    
</tramo>
<tramo>
    <distancia unidad="m" valor="78.70"></distancia>
    <coordenadas latitud="25.488881328395625" longitud="51.45985000981123" altitud="12"></coordenadas>
    <sector>"3"</sector>    
</tramo>
<tramo>
    <distancia unidad="m" valor="86.64"></distancia>
    <coordenadas latitud="25.488133391681075" longitud="51.459829545407565" altitud="12"></coordenadas>
    <sector>"3"</sector>    
</tramo>
<tramo>
    <distancia unidad="m" valor="120.44"></distancia>
    <coordenadas latitud="25.487213233400364" longitud="51.45918794472061" altitud="12"></coordenadas>
    <sector>"3"</sector>    
</tramo>
<tramo>
    <distancia unidad="m" valor="93.78"></distancia>
    <coordenadas latitud="25.48691135544504" longitud="51.458395976186445" altitud="13"></coordenadas>
    <sector>"3"</sector>    
</tramo>
<tramo>
    <distancia unidad="m" valor="232.52"></distancia>
    <coordenadas latitud="25.487330585788857" longitud="51.456120259533094" altitud="13"></coordenadas>
    <sector>"3"</sector>    
</tramo>
<tramo>
    <distancia unidad="m" valor="70.54"></distancia>
    <coordenadas latitud="25.487118180941472" longitud="51.45549997903597" altitud="12"></coordenadas>
    <sector>"3"</sector>    
</tramo>
<tramo>
    <distancia unidad="m" valor="374.01"></distancia>
    <coordenadas latitud="25.484132978887427" longitud="51.4537819521271" altitud="13"></coordenadas>
    <sector>"3"</sector>    
</tramo>
<tramo>
    <distancia unidad="m" valor="119.33"></distancia>
    <coordenadas latitud="25.48404541310976" longitud="51.45276979589921" altitud="14"></coordenadas>
    <sector>"3"</sector>    
</tramo>
<tramo>
    <distancia unidad="m" valor="657.58"></distancia>
    <coordenadas latitud="25.48921667256589" longitud="51.449597572710495" altitud="12"></coordenadas>
    <sector>"3"</sector>    
</tramo>
</tramos>

</circuito>
